Document: libmbfl
Title: Debian libmbfl Manual
Author: <insert document author here>
Abstract: This manual describes what libmbfl is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/libmbfl/libmbfl.sgml.gz

Format: postscript
Files: /usr/share/doc/libmbfl/libmbfl.ps.gz

Format: text
Files: /usr/share/doc/libmbfl/libmbfl.text.gz

Format: HTML
Index: /usr/share/doc/libmbfl/html/index.html
Files: /usr/share/doc/libmbfl/html/*.html
